# Generated by Django 5.2.1 on 2025-05-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='popularity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
