# Generated by Django 5.2.1 on 2025-06-04 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_festival_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.chinacity'),
        ),
    ]
