# Generated by Django 5.2.1 on 2025-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_excursion_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='theme',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
